### ISSUE TITLE
Specify grafana username/password

### ISSUE THREAD

**Issue by marbu** [linux-system-roles/metrics#100] opened 2021-12-12 00:30 UTC
When you use `metrics` role with `metrics_graph_service` set to true, and then login to grafana instance for the 1st time, you need to change username and password. But then when you run a playbook with the metrics role again, it fails on `Ensure graphing service runtime settings are configured` task since now ansible can't login to grafana.

```
TASK [/usr/share/linux-system-roles/metrics/roles/grafana : Ensure graphing service runtime settings are configured] ***                           
fatal: [centos]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content": "{\"message\":\"invalid username or p
assword\"}", "content_length": "42", "content_type": "application/json; charset=UTF-8", "date": "Sat, 11 Dec 2021 23:26:16 GMT", "elapsed": 0, "exp
ires": "-1", "json": {"message": "invalid username or password"}, "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized", "pragma
": "no-cache", "redirected": false, "status": 401, "url": "http://admin:admin@localhost:3000/api/plugins/performancecopilot-pcp-app/settings", "x_c
ontent_type_options": "nosniff", "x_frame_options": "deny", "x_xss_protection": "1; mode=block"}
```

Would it be possible to specify grafana username/password to prevent this failure? Ideally I would like to set the password directly in the playbook to avoid setting it for the first time, but I'm not sure if grafana provides a simple way to do that.

**Comment by natoscott** [comment] 2021-12-13 00:28
This is a duplicate of #26 - recently resolved for current versions of Grafana which provide a provisioning API.

**Closed by natoscott** 2021-12-13 00:28 UTC
